use_frameworks!

platform :ios, '9.0'

target 'ChaosAudioVisualizer_Example' do
  pod 'ChaosAudioVisualizer', :path => '../'

  target 'ChaosAudioVisualizer_Tests' do
    inherit! :search_paths

    
  end
end
